namespace Common
{
    public static class DemoLicense
    {
        public const string Licensee = "DEMO";
        public const string LicenseKey = "eyJTb2xkRm9yIjowLjAsIktleVByZXNldCI6NiwiU2F2ZUtleSI6ZmFsc2UsIkxlZ2FjeUtleSI6ZmFsc2UsIlJlbmV3YWxTZW50VGltZSI6IjAwMDEtMDEtMDFUMDA6MDA6MDAiLCJhdXRoIjoiREVNTyIsImV4cCI6IjIwMjEtMDgtMjFUMDE6MDA6MDMuMzMzMTM0NSswMTowMCIsImlhdCI6IjIwMjEtMDctMjJUMDA6MDA6MDMiLCJvcmciOiJERU1PIiwiYXVkIjoyfQ==.cdpWbVtbFkjvkyVLJMM9ufKBz80j8ZSRNfWELjgJ4Q6UFr3AS7p/mDNS+EIP1zMTeFX/3JMbK8Jabl5sw6DjqKfQuu0kHJ7L96eGoEshFP3aQlIoMLSWtzJ3SLXeDKrUFyJpp+7zAPFn6w9iOhfkhvYJxpcDeSXd8goYvQVNQP+vFKNY5gt/aYCkHi6ZDXkYLMSC4JJ6whYgkYKPNa7eOmkTEaVJEvJMh5QHv+DvHIhnKIlqRknNowGJfYmnkYR2zc4HwVcpgA7PshzyGDkc4PlgtM/TLYqIOG+Q0bCATpu766J7M2WLTXGJ079s4SyQjbp+X7XtT+WTG8E/jDNzOjov3mH3Ud7yrDzxSygPodetmkBrW/NT0Cval0xITq4/lNjspMs9NXutrkx2RxUpue4GVsLTroHP4MGxLEgjsoBmpiLFYoublw/odW97CTepxUGos7PPmhKSPO8uGdr5vUO6tpqX5iwusg2a1RqKgU5vDlFNpQGyzSoQFlTuojlQxZRAxXKYuWrOLklReF4cGfoPjxkNptY3kwnSOnqUgMeHwaHRWMlppleknzqujdwLAKtCehYVREDBUmpJAsFQ8tCPkq2mQ6x5Omm0KQmdFPpJMhcHoiMuo6I+JzSEHb3L9k58hxGbHQuKrIj0AOWZ/SlUcdFfbjL+mIDEks6b08w=";
    }
}